//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
	public class PlayerStateManager
	{
		private static ActiveState activeState = new ActiveState();
		private static DeadState deadState = new DeadState();

		private static PlayerStateContext context = new PlayerStateContext();

		public PlayerStateManager ()
		{

		}

		public static string GetState(){
			return context.GetState ().ToString ();
		}

		public static void SetState(string state){

			switch (state) {

			case "active":
				activeState.DoAction(context);
				break;
			case "dead":
				deadState.DoAction(context);
				break;

			}

		}
	}
}

