//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
	public abstract class ScoreObserver : IScoreObserver
	{
		protected string observerState;
		protected ScoreSubject scoreSubject;
		protected int score = 0;

		protected int currentScore;

		public abstract void Update (int newScore);
		public abstract void AddScore(int newScore);

		/*public ScoreObserver (ScoreSubject scoreSubject)
		{
			this.scoreSubject = scoreSubject;
		}

		public void Update(){

		}

		public void ShowState(){
			Debug.Log ("Observer : " + observerState);
		}*/

	}
}

