//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using AssemblyCSharp;
using UnityEngine;
namespace AssemblyCSharp
{
	public class Scorer
	{
		private static ScoreSubject scoreSubject = new ScoreSubject();

		private static TimeScore timeScore = new TimeScore (scoreSubject);
		private static PointScore pointScore = new PointScore (scoreSubject);

		public Scorer ()
		{
			//scoreSubject = new ScoreSubject();
			//timeScore = new TimeScore (scoreSubject);
			//pointScore = new PointScore (scoreSubject);
		}
		
		//Score adder for gumball
		public static void ScoreAdderForGumballs(string objectName ){

			//Debug.Log (scoreSubject.getScore ());

			switch(objectName){

				case "green":case "blue":case "yellow":case "red":
				pointScore.AddScore(2);
					//add 2 points
					break;
				case "pink":case "purple":
				pointScore.AddScore(4);
					//add 4 points
					break;
				case "star":
				pointScore.AddScore(6);
					//add 6 points
					break;
			}
		}

		public static void ScoreAdderForTime(int score){
			timeScore.AddScore (score);
		}

		public static int GetScore(){
			return scoreSubject.getScore ();
		}

		public static void SetScore(int score){
			scoreSubject.setScore (score);
		}

	}
}

