//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;
namespace AssemblyCSharp
{
	public class ScoreSubject : IScoreSubject
	{
		public ScoreSubject ()
		{

		}

		private int score = 0;
		
		private ArrayList observers = new ArrayList ();

		public void Attach(IScoreObserver ob){
			observers.Add (ob);
		}

		public void Detach(IScoreObserver ob){
			observers.Remove (ob);
		}

		public void NotifyObservers(){
			foreach (IScoreObserver ob in observers) {
				ob.Update(score);
			}
		}

		public int getScore(){
			return score;
		}

		public void setScore(int score){
			this.score = score;
			NotifyObservers ();
		}

		public void ShowState(){
			Debug.Log ("Subject State" + score);
		}

	}
}

