//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class SpeedManager
	{

		private RollingCharacterController character;
		SpeedContext speedContext;

		public SpeedManager (RollingCharacterController character)
		{
			this.character = character;
		}

		public void SetNewSpeed(string speedType){
			switch(speedType){

			case "low":
				new SpeedContext(new LowSpeedStrategy()).executeStrategy(character, 15);
				break;
			case "medium":
				new SpeedContext(new MediumSpeedStrategy()).executeStrategy(character, 20);
				break;
			case "high":
				new SpeedContext(new HighSpeedStrategy()).executeStrategy(character, 30);
				break;

			}
		}


	}
}

